server:
  port: 16666
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        #教师服务的路由规则
        - uri: lb://web-teacher
          predicates:
           - Path=/back/**
          filters:
            #配置一个自带的过滤器，该过滤器的作用表示会过滤掉请求的第一层路径
            - StripPrefix=1
        #学生服务的路由规则
        - uri: lb://web-student
          predicates:
           - Path=/**